index:
    path: /{page}
    controller: App\Controller\MainController::index
    defaults:
        page: 1
    requirements:
        page: '\d+'

demo:
    path: /demo
    controller: App\Controller\DemoController:index